name = "TulipIndicators"
uuid = "245c46a6-c642-460a-b06d-d3e7f4fd5245"
authors = ["kevindirect <git@kevindirect.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
TulipIndicators_jll = "b73d36f2-ba1b-519d-99df-fa501440d401"
