"""
Definitions file autogenerated by Clang.jl
"""

const TC_REAL = Cdouble

mutable struct tc_result end

const tc_set = UInt64

struct tc_config
	period::Cint
	body_none::TC_REAL
	body_short::TC_REAL
	body_long::TC_REAL
	wick_none::TC_REAL
	wick_long::TC_REAL
	near::TC_REAL
end

struct tc_hit
	index::Cint
	patterns::tc_set
end

# typedef int ( * tc_candle_function ) ( int size , TC_REAL const * const * inputs , tc_config const * options , tc_result * output )
const tc_candle_function = Ptr{Cvoid}

struct tc_candle_info
	name::Ptr{Cchar}
	full_name::Ptr{Cchar}
	pattern::tc_set
	candle::tc_candle_function
end

# typedef int ( * ti_indicator_start_function ) ( TI_REAL const * options )
const ti_indicator_start_function = Ptr{Cvoid}

# typedef int ( * ti_indicator_function ) ( int size , TI_REAL const * const * inputs , TI_REAL const * options , TI_REAL * const * outputs )
const ti_indicator_function = Ptr{Cvoid}

mutable struct ti_stream end

# typedef int ( * ti_indicator_stream_new ) ( TI_REAL const * options , ti_stream * * stream )
const ti_indicator_stream_new = Ptr{Cvoid}

# typedef int ( * ti_indicator_stream_run ) ( ti_stream * stream , int size , TI_REAL const * const * inputs , TI_REAL * const * outputs )
const ti_indicator_stream_run = Ptr{Cvoid}

# typedef void ( * ti_indicator_stream_free ) ( ti_stream * stream )
const ti_indicator_stream_free = Ptr{Cvoid}

struct ti_indicator_info
	name::Ptr{Cchar}
	full_name::Ptr{Cchar}
	start::ti_indicator_start_function
	indicator::ti_indicator_function
	indicator_ref::ti_indicator_function
	type::Cint
	inputs::Cint
	options::Cint
	outputs::Cint
	input_names::NTuple{16, Ptr{Cchar}}
	option_names::NTuple{16, Ptr{Cchar}}
	output_names::NTuple{16, Ptr{Cchar}}
	stream_new::ti_indicator_stream_new
	stream_run::ti_indicator_stream_run
	stream_free::ti_indicator_stream_free
end

const TC_VERSION = "0.9.2"

const TC_BUILD = 1660687722

const TC_OKAY = 0

const TC_INVALID_OPTION = 1

const TC_OUT_OF_MEMORY = 2

const TC_CANDLE_COUNT = 26

const TC_NONE = 0

const TC_ALL = Clong(1) << 26 - 1

const TC_ABANDONED_BABY_BEAR = Clong(1) << 0

const TC_ABANDONED_BABY_BULL = Clong(1) << 1

const TC_BIG_BLACK_CANDLE = Clong(1) << 2

const TC_BIG_WHITE_CANDLE = Clong(1) << 3

const TC_BLACK_MARUBOZU = Clong(1) << 4

const TC_DOJI = Clong(1) << 5

const TC_DRAGONFLY_DOJI = Clong(1) << 6

const TC_ENGULFING_BEAR = Clong(1) << 7

const TC_ENGULFING_BULL = Clong(1) << 8

const TC_EVENING_DOJI_STAR = Clong(1) << 9

const TC_EVENING_STAR = Clong(1) << 10

const TC_FOUR_PRICE_DOJI = Clong(1) << 11

const TC_GRAVESTONE_DOJI = Clong(1) << 12

const TC_HAMMER = Clong(1) << 13

const TC_HANGING_MAN = Clong(1) << 14

const TC_INVERTED_HAMMER = Clong(1) << 15

const TC_LONG_LEGGED_DOJI = Clong(1) << 16

const TC_MARUBOZU = Clong(1) << 17

const TC_MORNING_DOJI_STAR = Clong(1) << 18

const TC_MORNING_STAR = Clong(1) << 19

const TC_SHOOTING_STAR = Clong(1) << 20

const TC_SPINNING_TOP = Clong(1) << 21

const TC_STAR = Clong(1) << 22

const TC_THREE_BLACK_CROWS = Clong(1) << 23

const TC_THREE_WHITE_SOLDIERS = Clong(1) << 24

const TC_WHITE_MARUBOZU = Clong(1) << 25

const TI_VERSION = "0.9.2"

const TI_BUILD = 1660687722

const TI_REAL = Float64

const TI_INDICATOR_COUNT = 104

const TI_OKAY = 0

const TI_INVALID_OPTION = 1

const TI_OUT_OF_MEMORY = 2

const TI_TYPE_OVERLAY = 1

const TI_TYPE_INDICATOR = 2

const TI_TYPE_MATH = 3

const TI_TYPE_SIMPLE = 4

const TI_TYPE_COMPARATIVE = 5

const TI_MAXINDPARAMS = 16

const TI_INDICATOR_ABS_INDEX = 0

const TI_INDICATOR_ACOS_INDEX = 1

const TI_INDICATOR_AD_INDEX = 2

const TI_INDICATOR_ADD_INDEX = 3

const TI_INDICATOR_ADOSC_INDEX = 4

const TI_INDICATOR_ADX_INDEX = 5

const TI_INDICATOR_ADXR_INDEX = 6

const TI_INDICATOR_AO_INDEX = 7

const TI_INDICATOR_APO_INDEX = 8

const TI_INDICATOR_AROON_INDEX = 9

const TI_INDICATOR_AROONOSC_INDEX = 10

const TI_INDICATOR_ASIN_INDEX = 11

const TI_INDICATOR_ATAN_INDEX = 12

const TI_INDICATOR_ATR_INDEX = 13

const TI_INDICATOR_AVGPRICE_INDEX = 14

const TI_INDICATOR_BBANDS_INDEX = 15

const TI_INDICATOR_BOP_INDEX = 16

const TI_INDICATOR_CCI_INDEX = 17

const TI_INDICATOR_CEIL_INDEX = 18

const TI_INDICATOR_CMO_INDEX = 19

const TI_INDICATOR_COS_INDEX = 20

const TI_INDICATOR_COSH_INDEX = 21

const TI_INDICATOR_CROSSANY_INDEX = 22

const TI_INDICATOR_CROSSOVER_INDEX = 23

const TI_INDICATOR_CVI_INDEX = 24

const TI_INDICATOR_DECAY_INDEX = 25

const TI_INDICATOR_DEMA_INDEX = 26

const TI_INDICATOR_DI_INDEX = 27

const TI_INDICATOR_DIV_INDEX = 28

const TI_INDICATOR_DM_INDEX = 29

const TI_INDICATOR_DPO_INDEX = 30

const TI_INDICATOR_DX_INDEX = 31

const TI_INDICATOR_EDECAY_INDEX = 32

const TI_INDICATOR_EMA_INDEX = 33

const TI_INDICATOR_EMV_INDEX = 34

const TI_INDICATOR_EXP_INDEX = 35

const TI_INDICATOR_FISHER_INDEX = 36

const TI_INDICATOR_FLOOR_INDEX = 37

const TI_INDICATOR_FOSC_INDEX = 38

const TI_INDICATOR_HMA_INDEX = 39

const TI_INDICATOR_KAMA_INDEX = 40

const TI_INDICATOR_KVO_INDEX = 41

const TI_INDICATOR_LAG_INDEX = 42

const TI_INDICATOR_LINREG_INDEX = 43

const TI_INDICATOR_LINREGINTERCEPT_INDEX = 44

const TI_INDICATOR_LINREGSLOPE_INDEX = 45

const TI_INDICATOR_LN_INDEX = 46

const TI_INDICATOR_LOG10_INDEX = 47

const TI_INDICATOR_MACD_INDEX = 48

const TI_INDICATOR_MARKETFI_INDEX = 49

const TI_INDICATOR_MASS_INDEX = 50

const TI_INDICATOR_MAX_INDEX = 51

const TI_INDICATOR_MD_INDEX = 52

const TI_INDICATOR_MEDPRICE_INDEX = 53

const TI_INDICATOR_MFI_INDEX = 54

const TI_INDICATOR_MIN_INDEX = 55

const TI_INDICATOR_MOM_INDEX = 56

const TI_INDICATOR_MSW_INDEX = 57

const TI_INDICATOR_MUL_INDEX = 58

const TI_INDICATOR_NATR_INDEX = 59

const TI_INDICATOR_NVI_INDEX = 60

const TI_INDICATOR_OBV_INDEX = 61

const TI_INDICATOR_PPO_INDEX = 62

const TI_INDICATOR_PSAR_INDEX = 63

const TI_INDICATOR_PVI_INDEX = 64

const TI_INDICATOR_QSTICK_INDEX = 65

const TI_INDICATOR_ROC_INDEX = 66

const TI_INDICATOR_ROCR_INDEX = 67

const TI_INDICATOR_ROUND_INDEX = 68

const TI_INDICATOR_RSI_INDEX = 69

const TI_INDICATOR_SIN_INDEX = 70

const TI_INDICATOR_SINH_INDEX = 71

const TI_INDICATOR_SMA_INDEX = 72

const TI_INDICATOR_SQRT_INDEX = 73

const TI_INDICATOR_STDDEV_INDEX = 74

const TI_INDICATOR_STDERR_INDEX = 75

const TI_INDICATOR_STOCH_INDEX = 76

const TI_INDICATOR_STOCHRSI_INDEX = 77

const TI_INDICATOR_SUB_INDEX = 78

const TI_INDICATOR_SUM_INDEX = 79

const TI_INDICATOR_TAN_INDEX = 80

const TI_INDICATOR_TANH_INDEX = 81

const TI_INDICATOR_TEMA_INDEX = 82

const TI_INDICATOR_TODEG_INDEX = 83

const TI_INDICATOR_TORAD_INDEX = 84

const TI_INDICATOR_TR_INDEX = 85

const TI_INDICATOR_TRIMA_INDEX = 86

const TI_INDICATOR_TRIX_INDEX = 87

const TI_INDICATOR_TRUNC_INDEX = 88

const TI_INDICATOR_TSF_INDEX = 89

const TI_INDICATOR_TYPPRICE_INDEX = 90

const TI_INDICATOR_ULTOSC_INDEX = 91

const TI_INDICATOR_VAR_INDEX = 92

const TI_INDICATOR_VHF_INDEX = 93

const TI_INDICATOR_VIDYA_INDEX = 94

const TI_INDICATOR_VOLATILITY_INDEX = 95

const TI_INDICATOR_VOSC_INDEX = 96

const TI_INDICATOR_VWMA_INDEX = 97

const TI_INDICATOR_WAD_INDEX = 98

const TI_INDICATOR_WCPRICE_INDEX = 99

const TI_INDICATOR_WILDERS_INDEX = 100

const TI_INDICATOR_WILLR_INDEX = 101

const TI_INDICATOR_WMA_INDEX = 102

const TI_INDICATOR_ZLEMA_INDEX = 103

